### ISSUE TITLE
Scrolling messes up the UI.

### ISSUE THREAD

**Issue by thebitbrine** [J05HI/DeezLoadr#13] opened 2017-11-25 13:08 UTC
whenever you scroll up the list it begins to write the "downloaded" message at the last visible line of the console which ultimately messes the UI and it doesn't get fixed you you scroll down to where it was.

![](https://i.imgur.com/kqsjgrn.jpg)

**Comment by J05HI** [comment] 2017-11-25 14:30
@thebitbrine
Okay really strange
I'll look at it

**Comment by J05HI** [comment] 2017-11-26 14:17
@thebitbrine 
I can't reproduce this :(
Which OS are you using?

**Comment by thebitbrine** [comment] 2017-11-27 16:06
just scrolled up to the top while it was downloading a kept it there for a few seconds.
My guess is when you want to write a message you don't use the consoles default way.
The thing you do is move the cursor to the new line (which in this case is the last visible line on the console which shouldn't be this way) and then you start writing the message and it messes up.
PS: I'm not sure if this is a framework bug that you're using or just a wrong WriteLine method.

**Comment by J05HI** [comment] 2017-11-27 16:38
@thebitbrine
Must be a bug of the status lib :(
Will take a look at it, or wait for the GUI because it's not really high priority.

**Comment by thebitbrine** [comment] 2017-11-27 17:31
Okay thank, BTW i would like to help with the GUI i was wondering about building a GUI for this in WPF, but as i'm not a nodeJS expert i'll need some help.
If its in your interests, let me know ;)

**Comment by tazitus** [comment] 2017-11-27 17:39
>building a GUI for this in WPF

I don't think this is a good idea (or even possible)? It's probably far easier to do that using html/css and wrap in in electron.

**Comment by J05HI** [comment] 2017-11-27 18:08
Yeah I would like to build it with Electron because I'll go much faster and the design will be better :)

**Comment by J05HI** [comment] 2017-11-30 21:58
@thebitbrine
Will try to fix this soon :)
Maby using another status indicator lib.

**Comment by J05HI** [comment] 2017-12-10 17:05
Won't fix this anymore because it's not a really big bug.
Will be fixed with the GUI.

**Closed** 2017-12-10 17:05 UTC
Labels: Bug, For GUI
