### ISSUE TITLE
Doesn't download more than one song at once

### ISSUE THREAD

**Issue by painlessjeff** [J05HI/DeezLoadr#84] opened 2017-12-10 18:11 UTC
As the title says, it doesn't download more than one song at once. It downloads one song than exits, No error message or nothing. Album or playlists, same thing. BTW, it only does it using FLAC quality. Don't know if it fails on the tagging process. Thanks for this amazing tool.

**Comment by tabepic** [comment] 2017-12-10 18:21
I can confirm that as of commit f7955264bcd13e1761570fead5cbf88391874a34, DeezLoadr stops after succesfully downloading one song from a playlist.
Although, when I tested it, if the first song was already downloaded it would still move on to the next one (and then quit after downloading that one).

Currently `git bisect`ing...

**Comment by tabepic** [comment] 2017-12-10 18:25
Commit ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6 broke it as far as my testing goes.

**Comment by painlessjeff** [comment] 2017-12-10 18:26
Can confirm this commit as well after testing multiple commits. It start with that one.

**Comment by tabepic** [comment] 2017-12-10 18:59
Wait a minute... that's the commit when it switched to using flac binaries right?

The downloaded files don't have flac tags...
I'm pretty sure the new way of using the [meta]flac binaries isn't working.

**Comment by tabepic** [comment] 2017-12-10 19:11
@painlessjeff What OS are you running?

**Comment by painlessjeff** [comment] 2017-12-10 19:48
I'm running Arch Linux (x64)

**Comment by tabepic** [comment] 2017-12-10 19:50
Same here. Think I just found the issue:
- run `node DeezLoadr.js`
- leave it at the quality selection screen
- notice there is a DeezLoadrTemp folder
- notice how in DeezLoadrTemp/binaries/ how _nothing is actually set executable_

**Comment by painlessjeff** [comment] 2017-12-10 19:53
Yeah that's it. Just marked these two with exec bit in the TEMP folder and it works. But what's weird is that I marked exec the files in the original binaries folder and the bit is not respected in the Temp folder.

**Comment by tabepic** [comment] 2017-12-10 19:54
Yeah, it doesn't preserve permissions when it copies the binaries to the temp folder.

**Comment by J05HI** [comment] 2017-12-10 20:23
Oh Linux...
Can't test that.

**Comment by J05HI** [comment] 2017-12-10 20:24
@tabepic 
Must copy it to temp because i can't execute it in the app itself.

**Comment by J05HI** [comment] 2017-12-10 20:24
Maybe I should set the permission after copying

**Comment by tabepic** [comment] 2017-12-10 20:25
You mean it doesn't work if it's packaged?

**Comment by J05HI** [comment] 2017-12-10 20:25
@tabepic

**Comment by J05HI** [comment] 2017-12-10 20:26
@tabepic

**Comment by tabepic** [comment] 2017-12-10 20:27
755

**Comment by tabepic** [comment] 2017-12-10 20:27
fs.chmodSync(binary, '755') should do it

**Comment by J05HI** [comment] 2017-12-10 20:28
@tabepic 
Yeah thanks!
But only on Linux and MacOS?

**Comment by tabepic** [comment] 2017-12-10 20:28
Yeah, I'm not sure it will work on Windows at all.

**Comment by J05HI** [comment] 2017-12-10 22:01
Fixed now!
An album save bug could have been a problem, too.

**Closed** 2017-12-10 22:02 UTC
Labels: Bug

**Comment by J05HI** [comment] 2017-12-14 21:06
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
