### ISSUE TITLE
[Bug] Corrupted FLAC downloads.

### ISSUE THREAD

**Issue by stephanie00100** [J05HI/DeezLoadr#72] opened 2017-12-08 18:06 UTC
Tested with FLAC Frontend.

02 Skygaze.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

02 Skygaze.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_READ_FRAME
03 This Field.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

03 This Field.flac: ERROR while decoding data
                    state = FLAC__STREAM_DECODER_READ_FRAME
04 A Vital Gap.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

04 A Vital Gap.flac: ERROR while decoding data
                     state = FLAC__STREAM_DECODER_READ_FRAME
05 Something Like.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

05 Something Like.flac: ERROR while decoding data
                        state = FLAC__STREAM_DECODER_READ_FRAME
06 Dream Used to Have.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

06 Dream Used to Have.flac: ERROR while decoding data
                            state = FLAC__STREAM_DECODER_READ_FRAME
07 Ascend.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

07 Ascend.flac: ERROR while decoding data
                state = FLAC__STREAM_DECODER_READ_FRAME
08 Ending.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

08 Ending.flac: ERROR while decoding data
                state = FLAC__STREAM_DECODER_READ_FRAME
01 Ballad I.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

01 Ballad I.flac: ERROR while decoding data
                  state = FLAC__STREAM_DECODER_READ_FRAME

**Comment by J05HI** [comment] 2017-12-08 18:07
@stephanie00100
Could you please describe your problem better :)

**Comment by stephanie00100** [comment] 2017-12-08 18:24
These are the results from running a (test for errors) using FLAC Frontend. I think they are corrupted in some way, if they were fine, they should come back as this.

01 - Constant Vacation.flac: ok
02 - Taking it All Away.flac: ok
03 - in the Sunshine.flac: ok

**Comment by tazitus** [comment] 2017-12-08 18:32
Have you tried redownloading them? Sometimes files (cached?) on a specific CDN proxy are corrupted. Because the CDN proxy used is random every time, just downloading the files again might solve your problem.

I've only seen this happen with a few singular tracks though, not whole albums.

**Comment by stephanie00100** [comment] 2017-12-08 18:46
Tried it again, plus a completely different album/artist, same result. Do you think this happened because I tried using the latest build? Meaning, I'm very new with Github builds, that was the first successful build/compile I've ever done of any latest build.

02 Revenge.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


02 Revenge.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_READ_FRAME
03 Whatever You Want.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


03 Whatever You Want.flac: ERROR while decoding data
                           state = FLAC__STREAM_DECODER_READ_FRAME
04 What About Us.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


04 What About Us.flac: ERROR while decoding data
                       state = FLAC__STREAM_DECODER_READ_FRAME
05 But We Lost It.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


05 But We Lost It.flac: ERROR while decoding data
                        state = FLAC__STREAM_DECODER_READ_FRAME
06 Barbies.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


06 Barbies.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_READ_FRAME
07 Where We Go.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


07 Where We Go.flac: ERROR while decoding data
                     state = FLAC__STREAM_DECODER_READ_FRAME
08 For Now.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


08 For Now.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_READ_FRAME
09 Secrets.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


09 Secrets.flac: ERROR while decoding data
                 state = FLAC__STREAM_DECODER_READ_FRAME
10 Better Life.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


10 Better Life.flac: ERROR while decoding data
                     state = FLAC__STREAM_DECODER_READ_FRAME
11 I Am Here.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


11 I Am Here.flac: ERROR while decoding data
                   state = FLAC__STREAM_DECODER_READ_FRAME
12 Wild Hearts Can't Be Broken.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


12 Wild Hearts Can't Be Broken.flac: ERROR while decoding data
                                     state = FLAC__STREAM_DECODER_READ_FRAME
13 You Get My Love.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


13 You Get My Love.flac: ERROR while decoding data
                         state = FLAC__STREAM_DECODER_READ_FRAME
01 Beautiful Trauma.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


01 Beautiful Trauma.flac: ERROR while decoding data
                          state = FLAC__STREAM_DECODER_READ_FRAME

**Comment by tazitus** [comment] 2017-12-08 19:02
Can you try compiling the version from commit https://github.com/J05HI/DeezLoadr/commit/73a701ba06f619d53e0fd318c2c90aabe994ab86? After that there has been some cleanup in the download function, that might have introduced an error.

**Comment by J05HI** [comment] 2017-12-08 19:09
@tazitus
This was a bug fix.
I think the flac tagging is the problem.

**Comment by RandomNinjaAtk** [comment] 2017-12-08 19:12
I have more testing to do, but before the flac tagging was resolved. It did not produce corrupted FLAC files. After tagging was fixed, it does. I plan to play around with it more. I want to isolate if its the VORBIS comments or coverart that is possibly causing the corruption. Or maybe its both...

**Comment by RandomNinjaAtk** [comment] 2017-12-08 19:54
@tazitus "Can you try compiling the version from commit 73a701b? After that there has been some cleanup in the download function, that might have introduced an error."

Just tested from the commit you referenced and no corruption

**Comment by J05HI** [comment] 2017-12-08 20:12
@RandomNinjaAtk
Try this: [https://github.com/J05HI/DeezLoadr/commit/71611a675588ec8bba0203ba5cf5ff691e965d29](https://github.com/J05HI/DeezLoadr/commit/71611a675588ec8bba0203ba5cf5ff691e965d29)

**Comment by RandomNinjaAtk** [comment] 2017-12-08 20:35
@J05HI I believe that one definitely works, based on my previous testing.

So I tested the newest version more and I prevent it from removing and writing both picture and vorbis comments, the files passed as normal, no corruption.

I did try a few various combinations, no picture tag or no comments, but it wasn't till I removed both that the files passed the checks...

**Comment by FatKiwi** [comment] 2017-12-08 22:36
I can confirm this error with latest build.

**Comment by J05HI** [comment] 2017-12-08 22:48
@FatKiwi
Yeah but which one?
There is no working... :(

**Comment by FatKiwi** [comment] 2017-12-08 22:52
I think I found why. You need to specify mime type of artwork (image/jpeg). It doesn't show at all in MP3Tag. All my other songs from everywhere show correct mime type.

And cover itself is as Other instead of Front (but that doesn't affect it, although it's preferable to switch it).

**Comment by J05HI** [comment] 2017-12-08 22:57
@FatKiwi 
I'll try around a bit.
The lib must work :D

**Comment by FatKiwi** [comment] 2017-12-08 22:59
Definitely bug when writing artwork to FLAC. Try with mime type first.
Also error is gone if I reconvert the FLAC. It produces cleaner header, you should try it and compare how they look in hex.

But I definitely see mime type in the new header, while it's missing in yours.

**Comment by RandomNinjaAtk** [comment] 2017-12-09 00:03
@FatKiwi I tried both ways, only having text metadata without the coverart, and it still reported as being corrupt.

**Comment by J05HI** [comment] 2017-12-09 00:15
I have it!!!
Using metaflac now and works perfectly. After some test I'll implement it in the app tomorrow :)

**Comment by FatKiwi** [comment] 2017-12-09 09:42
Great job! What was the issue?

**Comment by J05HI** [comment] 2017-12-09 10:05
@FatKiwi
Yeah :)

**Comment by RandomNinjaAtk** [comment] 2017-12-09 19:50
@J05HI Any chance of pushing the new code soon so we can test it further?

**Comment by J05HI** [comment] 2017-12-09 21:14
@RandomNinjaAtk
Sorry I was busy today
Will start now :)

**Comment by mudlord** [comment] 2017-12-09 21:17
Neato.

**Comment by J05HI** [comment] 2017-12-10 00:20
FIxed with: [https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6](https://github.com/J05HI/DeezLoadr/commit/ab0d4aa8b0958c5eaf515b7cfc7151009e05e3d6)

I need someone who can add the flac and metaflac binaries for OSX and Linux.

**Comment by FatKiwi** [comment] 2017-12-10 00:21
Add them where?

**Comment by J05HI** [comment] 2017-12-10 00:24
Shit I can't build it :(
It doesn't add the binaries.

**Comment by FatKiwi** [comment] 2017-12-10 00:25
Oops!

**Comment by J05HI** [comment] 2017-12-10 00:38
@FatKiwi 
Try running node .\DeezLoadr.js
It should work then.

**Comment by J05HI** [comment] 2017-12-10 16:43
Build and try it now :)

**Closed by J05HI** 2017-12-10 16:43 UTC
Labels: Bug

**Comment by stephanie00100** [comment] 2017-12-10 18:10
Having trouble building it, not sure what I'm doing wrong.

D:\Downloads\Music\Programs\DeezLoadr> D:\Downloads\Music\Programs\DeezLoadr\BUILD.cmd

D:\Downloads\Music\Programs\DeezLoadr>rmdir /s /q BUILDS

D:\Downloads\Music\Programs\DeezLoadr>pkg package.json --targets latest-macos-x86,latest-macos-x64,latest-win-x86,latest-win-x64,latest-linux-x86,latest-linux-x64 --out-dir BUILDS
> pkg@4.3.0-beta.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v9.0.0-macos-x86     [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v9.0.0-macos-x86
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.0.0-macos-x86"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.0.0-macos-x86"}
> Building base binary from source:
  built-v9.0.0-macos-x86
> Error! Not able to build for 'macos' here, only for 'win'


D:\Downloads\Music\Programs\DeezLoadr> pkg package.json -t win-x64 --out-dir BUILDS
> pkg@4.3.0-beta.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v9.0.0-win-x64       [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v9.0.0-win-x64
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.0.0-win-x64"}
  fetched-v9.0.0-win-x64       [                    ] 1%> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v9.0.0-win-x64"}
> Building base binary from source:
  built-v9.0.0-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v9.0.0
> Applying patches

> Error! Error: spawn patch ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by tabepic** [comment] 2017-12-10 18:13
@stephanie00100 Did you try running `npm update pkg`?
It seems `pkg` recently updated and the older version broke.

**Comment by J05HI** [comment] 2017-12-10 18:29
Yeah `npm update pkg -g` should do this.

**Comment by stephanie00100** [comment] 2017-12-10 19:45
I can't win, now I get this.

D:\Downloads\Music\Programs\DeezLoadr> D:\Downloads\Music\Programs\DeezLoadr\BUILD.cmd

D:\Downloads\Music\Programs\DeezLoadr>rmdir /s /q BUILDS

D:\Downloads\Music\Programs\DeezLoadr>pkg package.json --targets latest-macos-x86,latest-macos-x64,latest-win-x86,latest-win-x64,latest-linux-x86,latest-linux-x64 --out-dir BUILDS
> pkg@4.3.0-beta.4
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v9.1.0-macos-x86     [====================] 100%
  fetched-v9.1.0-macos-x64     [====================] 100%
  fetched-v9.1.0-linux-x86     [====================] 100%
  fetched-v9.1.0-linux-x64     [====================] 100%
> Warning Cannot find module 'bluebird' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'chalk' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'fs-extra' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'inquirer' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'md5-file' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'node-id3' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'ora' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'request' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'request-promise' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'sanitize-filename' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'globby' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'chalk' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'ora' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'sanitize-filename' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'bluebird' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'request-promise' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'node-id3' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'md5-file' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'inquirer' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'fs-extra' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js
> Warning Cannot find module 'globby' from 'D:\Downloads\Music\Programs\DeezLoadr'
  D:\Downloads\Music\Programs\DeezLoadr\DeezLoadr.js

**Comment by tabepic** [comment] 2017-12-10 19:47
DId you run `npm install` and/or `npm update` in `D:\Downloads\Music\Programs\DeezLoadr`?

**Comment by stephanie00100** [comment] 2017-12-10 20:09
Only for pkg, I just ran that now. Now it works! Thank you everyone for the help.

**Comment by tabepic** [comment] 2017-12-10 20:10
No problem, trust me I've once spent a good 3 hours debugging something similar last week and it annoys me to no end. 😄

**Comment by stephanie00100** [comment] 2017-12-10 20:13
I used to be better with commands, I haven't used Linux in a very long time though. Ouch, that sounds painful.

**Comment by J05HI** [comment] 2017-12-14 21:07
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
