### ISSUE TITLE
flac is downloaded 100% but when it is played it is incomplete it is cut

### ISSUE THREAD

**Issue by fabriccioguzman** [J05HI/DeezLoadr#41] opened 2017-11-27 23:16 UTC
help flac is downloaded 100% but when it is played it is incomplete it is cut 
try this too: http://www.deezer.com/track/77111350 that skips to the end when playing

**Comment by FatKiwi** [comment] 2017-11-28 01:19
Problem is on your side. I cannot reproduce this. Downloaded this and works perfectly, no skipping.

**Comment by fabriccioguzman** [comment] 2017-11-28 03:55
wao, does it seriously reproduce you without problems? incredible to be my connection the problem
seriously it reproduces you without problems

**Comment by FatKiwi** [comment] 2017-11-28 05:00
Yes, no problems.
File size should be: 26.4 MB (27,729,481 bytes)
File MD5: E20951D671DF7E12605533B0D9D1F2FD

Check yours.

**Comment by J05HI** [comment] 2017-11-28 05:14
I'll try it to :)
And maybe add something to validate that the song has been successfully downloaded.

**Comment by J05HI** [comment] 2017-11-28 16:32
@fabriccioguzman 
I've currently downloaded it and it's complete

**Comment by jmicgz** [comment] 2017-11-28 17:35
This happens also to me and depends of music player for example:
VLC do the same thing @fabriccioguzman 
Clementine and Rhythmbox doesnt detect the flacs downloaded on imports (Flac tracks from other sources are imported well)
Cantata plays fine and import but cant advance forwards in the song.
Audacity plays fine.

Opened the track in vim and correct flac files all starts with header fLaC the ones downloaded with deezloadr no.
Gstreamer output:

WARNING: erroneous pipeline: no element "decodebin"

So... its generating corrupt flacs?

Using ubuntu 16.04

**Comment by fabriccioguzman** [comment] 2017-11-28 17:58
@FatKiwi @J05HI @jmicgz @azgul @jonaaa20 they are some but the majority happens to me this, also I have tried the scripts for tampermonkey and the same happens to me, it is as if it is not decrypting 100% it is badly decrypted

**Comment by fabriccioguzman** [comment] 2017-11-28 18:09
I also noticed that the flac file downloads them 100%, but when I look at the file size, for example: 24.87 mb, but when I play it, it is cut in the middle of the reproduction, but I delete it and download it again and verify the size and this time it weighs 27.88 mb but it is cut at the end and sometimes it

**Comment by J05HI** [comment] 2017-11-28 18:46
Really strange :(
I don't know what to do. Maybe it's on Deezers side.

**Comment by J05HI** [comment] 2017-11-28 18:48
Is it perfectly working on the website?

**Comment by omniusaspirer** [comment] 2017-11-28 18:59
Can one of you with this tool working download "Wesley's Theory" by Kendrick Lamar as FLAC? I attempted to adapt the original Deezloader to download FLAC and I got it working, but roughly 20-30% of the tracks downloaded were consistently corrupted, even on repeat download. Running "flac -wt" on the file returned a LOST_SYNC error.

**Comment by fabriccioguzman** [comment] 2017-11-28 19:29
@J05HI if I reproduce it well from deezer
this seems to me to be the speed of my internet since when deezloadr and the tampermonkey script generates the flac this has an expiration time

**Comment by bascurtiz** [comment] 2017-11-28 20:35
@omniusaspirer 
I did (using the 3 FLAC tools outthere at the moment) - see results in pics below:
https://imgur.com/a/K3PhO
All seems fine to me, incl. length.
I'm not sure if its related to internetspeed (as some think there's some expiration time), but my speeds according to speedtest.net are http://beta.speedtest.net/result/6832984561

**Comment by J05HI** [comment] 2017-11-28 20:52
@bascurtiz 
Nice picture :)
For me it's working fine, too.
My internet speed: [http://beta.speedtest.net/result/6833021255](http://beta.speedtest.net/result/6833021255)

**Comment by abba23** [comment] 2017-11-28 21:00
>Which tool should i use to run "flac -wt" on Windows?

You can get the reference decoder at https://xiph.org/flac/download.html
`flac -wt` decodes the file while watching for errors and checks the builtin checksum.

**Comment by omniusaspirer** [comment] 2017-11-28 21:24
@J05HI @bascurtiz 

Happy to report that after your most recent update I was able to use your tool. Checked out the files I was having corruption issues with and they're all showing as ok with none of the issues I was having before. Thanks for the hard work!

**Comment by J05HI** [comment] 2017-11-28 21:29
@omniusaspirer

Great!!! But I haven't touched anything there 😅

Can someone other confirm this?

**Comment by omniusaspirer** [comment] 2017-11-28 21:37
@J05HI 

hahah, to be clear, I mean that your fix to use the API instead of parsing the HTML has allowed me to use your tool now. The FLACs downloaded with Deezloadr are not showing the sporadic corruption issues I had with my own modified version of the original Deezloader. As to why your version doesn't have the issues, I'm not sure. Presumably some variation in how you're actually piecing together the files.

**Comment by J05HI** [comment] 2017-11-28 21:54
@omniusaspirer
Oh okay :D

**Comment by fabriccioguzman** [comment] 2017-11-28 23:09
@J05HI #34

**Comment by J05HI** [comment] 2017-11-30 21:52
@fabriccioguzman
Can you please check this on the newest build.

**Comment by J05HI** [comment] 2017-11-30 21:55
fabriccioguzman @omniusaspirer @bascurtiz @jmicgz 
Could you please check this on the newest build.

**Comment by fabriccioguzman** [comment] 2017-12-02 03:15
@J05HI 
huy joshi is still the same jumps the audio when playing it is cut
the strange thing that I downloaded it with the deezer plugin in athame and if it played perfectly

**Comment by J05HI** [comment] 2017-12-02 06:02
@fabriccioguzman
Really really strange :(

**Comment by J05HI** [comment] 2017-12-02 07:11
@fabriccioguzman 
Song downloads and plays fine with VLC and Groove Music.
Do you download this in a playlist or album?

**Comment by J05HI** [comment] 2017-12-02 07:56
@fabriccioguzman 
Added a MD5 check for flac files in the latest build.
Please report back if it says "Song "...": MD5 doesn't match Deezer's MD5."
If it doesn't I can't do anything.

**Comment by J05HI** [comment] 2017-12-04 05:07
@fabriccioguzman
Can I close this?

**Comment by FatKiwi** [comment] 2017-12-04 17:07
No MD5 text for now, all downloads complete for me. I think you can close it.

**Comment by J05HI** [comment] 2017-12-04 17:29
@FatKiwi 
Okay thx :)

PS: Flac tagging is ready soon :)

**Closed by J05HI** 2017-12-04 17:29 UTC
Labels: Bug

**Comment by J05HI** [comment] 2017-12-14 21:08
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
